# ======================================================
# STRESS ASSESSMENT QUESTION BANK
# ======================================================

QUESTIONS = {

    "academic": [

        "Do you often feel overwhelmed by your coursework?",
        "Do you struggle to meet assignment deadlines?",
        "Do you worry about failing your courses?",
        "Do you find it difficult to concentrate during lectures?",
        "Do examinations make you feel stressed?",
        "Do you procrastinate on academic work?",
        "Do you have enough time to study each day?",
        "Are your grades lower than you expected?",
        "Do you lose sleep because of school work?",
        "Do you understand most classroom lessons?",
        "Do you find balancing multiple courses difficult?",
        "Have you ever considered dropping a course because of stress?",
        "Do you feel pressure to maintain high grades?",
        "Are group assignments stressful for you?",
        "Do you feel confident before examinations?",
        "Do you miss classes because of stress?",
        "Do you find academic competition stressful?",
        "Do lecturers provide enough academic support?",
        "Do presentations make you anxious?",
        "Do you struggle with time management?",
        "Do academic responsibilities affect your happiness?",
        "Do you have adequate study materials?",
        "Do you compare your grades with classmates?",
        "Are practical sessions stressful?",
        "Do you worry about graduating on time?",
        "Does poor internet affect your studies?",
        "Do academic tasks prevent you from relaxing?",
        "Do you feel mentally exhausted after studying?",
        "Are you satisfied with your academic performance?",
        "Do surprise tests increase your stress?",
        "Do difficult topics frustrate you?",
        "Do classmates support you academically?",
        "Do poor grades discourage you?",
        "Do semester projects overwhelm you?",
        "Do you revise consistently?",
        "Do academics affect your social life?",
        "Do you find online learning stressful?",
        "Do lecturers communicate clearly?",
        "Do you panic before examinations?",
        "Do continuous assessments stress you?",
        "Do you stay motivated throughout the semester?",
        "Does fear of failure reduce your confidence?",
        "Do you ask for help when confused?",
        "Do family expectations increase academic pressure?",
        "Do you believe your workload is manageable?",
        "Do academics interfere with your responsibilities?",
        "Have you skipped meals because of studying?",
        "Do you experience burnout during the semester?",
        "Overall, is your academic life stressful?",
        "How confident are you in completing this semester successfully?"

    ],

    "financial": [

    "Do you worry about paying your school fees?",
    "Do financial problems make it difficult to concentrate on your studies?",
    "Do you often run out of money before the end of the month?",
    "Do you skip meals because of financial difficulties?",
    "Do transportation costs prevent you from attending lectures?",
    "Do you depend entirely on your parents or guardian for money?",
    "Do you worry about accommodation expenses?",
    "Do you borrow money frequently from friends?",
    "Do financial stress affect your academic performance?",
    "Do you struggle to buy textbooks or learning materials?",
    "Do unexpected expenses cause you stress?",
    "Do you have difficulty budgeting your money?",
    "Do you worry about future financial security?",
    "Have you considered dropping out because of financial issues?",
    "Do you work part-time to support yourself?",
    "Does your job interfere with your studies?",
    "Do you feel embarrassed asking others for money?",
    "Do financial problems affect your sleep?",
    "Do you avoid social activities because of money?",
    "Do you worry about paying examination fees?",
    "Do you feel stressed about daily living expenses?",
    "Do you struggle to buy food regularly?",
    "Do you compare your financial situation with classmates?",
    "Do you feel your allowance is enough?",
    "Do you save money regularly?",
    "Have financial issues delayed your registration?",
    "Do you worry about buying data or internet access?",
    "Do financial issues affect your mental health?",
    "Do you avoid asking for financial help?",
    "Do you worry about graduation expenses?",
    "Do you often think about money during lectures?",
    "Do you have debts that worry you?",
    "Do financial challenges reduce your motivation?",
    "Do you feel confident managing your finances?",
    "Do you receive financial support consistently?",
    "Do financial problems make you anxious?",
    "Do you struggle to afford medical care?",
    "Do you miss classes because of transportation costs?",
    "Do you find it difficult to plan your spending?",
    "Do you feel overwhelmed by financial responsibilities?",
    "Do you worry about future employment because of finances?",
    "Do you feel financially secure?",
    "Do money problems affect your relationships?",
    "Do financial worries reduce your happiness?",
    "Do you feel pressure to earn money while studying?",
    "Do financial challenges affect your confidence?",
    "Do you feel stressed when checking your account balance?",
    "Overall, are your finances a major source of stress?",
    "Do financial worries affect your daily decisions?",
    "How confident are you in managing your finances?"

],
    "family": [

    "Do you experience frequent conflicts at home?",
    "Do family problems affect your concentration in school?",
    "Do your parents or guardians put pressure on your academic performance?",
    "Do you feel emotionally supported by your family?",
    "Do family responsibilities interfere with your studies?",
    "Do you worry about a sick family member?",
    "Do financial problems in your family increase your stress?",
    "Do you feel comfortable discussing your problems with your family?",
    "Do you often argue with family members?",
    "Do you miss home while at school?",
    "Do family expectations make you anxious?",
    "Do you feel lonely because you are away from your family?",
    "Have family issues affected your grades?",
    "Do you receive enough encouragement from your family?",
    "Do family conflicts affect your sleep?",
    "Do you worry about disappointing your parents?",
    "Do you feel understood by your family?",
    "Do family problems reduce your motivation?",
    "Do family emergencies interrupt your studies?",
    "Do you feel responsible for solving family problems?",
    "Do you often think about family issues during lectures?",
    "Do family disagreements affect your mood?",
    "Do you feel neglected by your family?",
    "Do family members respect your educational goals?",
    "Do you worry about your siblings' wellbeing?",
    "Do family problems affect your confidence?",
    "Do you feel safe at home?",
    "Do you feel emotionally drained after family discussions?",
    "Do family responsibilities leave little time for studying?",
    "Do you feel guilty for being away from your family?",
    "Do you experience stress because of family expectations?",
    "Do you receive enough emotional support from home?",
    "Do family conflicts make you anxious?",
    "Do you feel appreciated by your family?",
    "Do family issues affect your attendance in class?",
    "Do you communicate regularly with your family?",
    "Do you feel pressured to succeed for your family's sake?",
    "Do family disagreements affect your happiness?",
    "Do you find it difficult balancing family and school responsibilities?",
    "Do family problems affect your mental health?",
    "Do you often feel homesick?",
    "Do family expectations increase your stress?",
    "Do you worry about your family's future?",
    "Do you feel isolated from your family?",
    "Do family issues affect your relationships with friends?",
    "Do you feel emotionally exhausted by family problems?",
    "Do you wish your family understood you better?",
    "Overall, is your family life a source of stress?",
    "Do family responsibilities reduce your academic focus?",
    "How supported do you feel by your family?"

],

  "health": [

    "Do you usually get at least 7 hours of sleep each night?",
    "Do you often feel tired during the day?",
    "Do you experience headaches because of stress?",
    "Do you skip meals regularly?",
    "Do you eat balanced and nutritious meals?",
    "Do you exercise at least three times a week?",
    "Do you often feel physically exhausted?",
    "Do you have difficulty falling asleep?",
    "Do you wake up feeling refreshed?",
    "Do you suffer from frequent illness?",
    "Do you drink enough water daily?",
    "Do you rely on caffeine to stay awake?",
    "Do you experience body pains due to stress?",
    "Do you often feel dizzy or weak?",
    "Do you struggle with maintaining a healthy lifestyle?",
    "Do you spend too much time on screens before sleeping?",
    "Do you feel your physical health affects your academics?",
    "Do you visit the hospital when necessary?",
    "Do you ignore health problems because of school work?",
    "Do you experience loss of appetite?",
    "Do you overeat when stressed?",
    "Do you feel energetic most days?",
    "Do you experience frequent anxiety symptoms?",
    "Do you find it difficult to relax?",
    "Do you often feel emotionally exhausted?",
    "Do you have trouble concentrating because of poor health?",
    "Do you experience mood swings?",
    "Do you feel healthy overall?",
    "Do you frequently suffer from stress-related fatigue?",
    "Do you have enough time to rest?",
    "Do you feel overwhelmed by your daily routine?",
    "Do you maintain good personal hygiene even during stressful periods?",
    "Do you experience chest discomfort when stressed?",
    "Do you practice relaxation techniques?",
    "Do you take breaks when studying for long hours?",
    "Do you often ignore signs of stress in your body?",
    "Do you feel physically stronger than you did six months ago?",
    "Do you sleep more when stressed?",
    "Do you experience frequent muscle tension?",
    "Do you believe stress has affected your health?",
    "Do you feel emotionally stable most days?",
    "Do you experience panic attacks?",
    "Do you feel your lifestyle is healthy?",
    "Do you have enough time for recreation?",
    "Do you regularly participate in physical activities?",
    "Do you think your health affects your academic success?",
    "Do you experience burnout frequently?",
    "Overall, do you consider yourself physically healthy?",
    "Do you believe your current lifestyle reduces stress?",
    "How satisfied are you with your overall health?"

],

    "social": [

    "Do you find it easy to make friends at school?",
    "Do you often feel lonely?",
    "Do you feel accepted by your classmates?",
    "Do you avoid social gatherings?",
    "Do you feel anxious when meeting new people?",
    "Do you have someone you can confide in?",
    "Do you feel supported by your friends?",
    "Do you compare yourself with others on social media?",
    "Do social media affect your self-esteem?",
    "Do you experience peer pressure?",
    "Do you feel left out in social situations?",
    "Do you enjoy participating in campus activities?",
    "Do you find it difficult to express your emotions?",
    "Do you often feel misunderstood?",
    "Do you feel confident speaking in groups?",
    "Do you worry about what others think of you?",
    "Do you often feel rejected?",
    "Do you have close friends you trust?",
    "Do arguments with friends affect your mood?",
    "Do you feel emotionally supported by people around you?",
    "Do you enjoy spending time with others?",
    "Do you experience bullying or harassment?",
    "Do you isolate yourself when stressed?",
    "Do you find it difficult to maintain friendships?",
    "Do you feel appreciated by your friends?",
    "Do you get anxious before social events?",
    "Do you often feel embarrassed in public?",
    "Do you have difficulty communicating your feelings?",
    "Do you feel comfortable asking for help?",
    "Do you often overthink conversations?",
    "Do you avoid interacting with classmates?",
    "Do you feel emotionally drained after social interactions?",
    "Do you believe you have good communication skills?",
    "Do you feel confident in yourself?",
    "Do you worry about being judged by others?",
    "Do you feel connected to your university community?",
    "Do you have healthy relationships with others?",
    "Do you forgive people easily?",
    "Do you experience frequent mood changes?",
    "Do you often feel unhappy without knowing why?",
    "Do you feel optimistic about your future?",
    "Do you handle criticism well?",
    "Do you become upset easily?",
    "Do you feel respected by those around you?",
    "Do you feel motivated by your friends?",
    "Do you find it difficult to trust people?",
    "Do you feel emotionally balanced?",
    "Overall, do social relationships contribute to your stress?",
    "Do you believe your emotional wellbeing is good?",
    "How satisfied are you with your social life?"

],

}